import { Pool, neonConfig } from '@neondatabase/serverless';
import fs from 'fs';
import path from 'path';
import ws from 'ws';
import 'dotenv/config';

neonConfig.webSocketConstructor = ws;

async function run() {
    const connectionString = process.env.DATABASE_URL;
    if (!connectionString) {
        throw new Error('DATABASE_URL is not set');
    }

    console.log('Connecting to Neon database via WebSocket...');
    const pool = new Pool({ connectionString });

    try {
        // Read the script generated by prisma migrate diff
        // The file is currently UTF-16LE because of PowerShell, we should handle that.
        const fileBuffer = fs.readFileSync(path.join(process.cwd(), 'scripts', 'migration.sql'));
        let script = '';

        // Check if it's UTF-16LE BOM
        if (fileBuffer.length >= 2 && fileBuffer[0] === 0xff && fileBuffer[1] === 0xfe) {
            script = fileBuffer.toString('utf16le');
        } else {
            script = fileBuffer.toString('utf8');
        }

        // Strip UTF-8 BOM if present
        if (script.charCodeAt(0) === 0xFEFF) {
            script = script.slice(1);
        }

        // Prisma migration scripts might contain multiple statements separated by ';'
        // but the neon query handles execution of multiple statements natively if no unparameterized conflicts exist.
        // However, CREATE EXTENSION requires its own execution usually or we can simply pass the whole block.
        console.log('Executing SQL payload...');
        await pool.query(script);

        console.log('Schema successfully pushed!');
    } catch (error) {
        console.error('Failed to push schema:', error);
        process.exit(1);
    } finally {
        await pool.end();
    }
}

run();
